### ISSUE TITLE
Enforce code style

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#1]
We should start using this on all repo:

https://github.com/editorconfig/editorconfig-visualstudio#readme

in order to have the same indent/space/tabs, etc...

**Comment by micdenny** [comment]
Never used, do you have any experience on it?

**Comment by mauroservienti** [comment]
no, I tried another extension but it was a mess. I'll give it a try in the next few days and share my comments here.

**Comment by micdenny** [comment]
I've only ever used the resharper one, but obviously is not an option here, they have some [license for open-source project](https://www.jetbrains.com/resharper/buy/choose_edition.jsp?license=OPEN_SOURCE), but it doesn't meet our criteria, and it's too restrictive, don't like.

What they do out there other open-source project? Maybe they use StyleCop?

**Comment by mauroservienti** [comment]
dunno :-)

**Comment by mauroservienti** [comment]
Repos are now using `.editorconfig`. This is done.
