### ISSUE TITLE
Evaluate gitter chat for GitHub

### ISSUE THREAD

**Issue by micdenny** [RadicalFx/housekeeping#14]
Could be nice to have an integrated "chat to the development team" as a added support feature.

[Gitter](https://gitter.im/) provide such a service, you can get unlimited public rooms and one-to-one chats, free forever.

See it in action on [ChocolateyGUI repo](https://github.com/chocolatey/ChocolateyGUI#support)

**Comment by mauroservienti** [comment]
I sent you both an invitation to join the team on Slack

**Comment by micdenny** [comment]
is it possible also to open a public channel where community can find us about radicalfx?

**Comment by mauroservienti** [comment]
Sincerely don't know :-)
Do we really want it?

Sent from my Amazing not anymore Yellow Lumia, typos are guaranteed ;-)

**Comment by micdenny** [comment]
Probably not, for sure issues are better to track problems, so forget about this :)
