### ISSUE TITLE
Separate Radical into multiple repositories

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#15]
The issue we are currently facing is that having all the projects, that ends up in different `NuGet` packages, complicates the release of a single package/project.
In light of having a [build server](https://github.com/RadicalFx/radical/issues/93) what I expect to be able to do is via `GitFlow`:
- define a feature;
- create a branch for the above feature;
- implement;
- finish the feature tagging the feature with the expected version, such as 1.3.0.1-Beta;
- push to the `develop`:
  - once pushed to the `develop` the build server kicks in, builds the project, creates the `NuGet` package and pushes it to `MyGet`;
- create via GitFlow a release
- do the required adjustments where needed;
- finish the release tagging it with the release number;
- push to 'master`:
  - once pushed to the `master` the build server kicks in, builds the project, creates the `NuGet` package and pushes it to `NuGet`;

Not only, having multiple repositories force us to think much more to features that span multiple projects. Only a good thing.

**Comment by mauroservienti** [comment]
@micdenny comments/thoughts?

**Comment by micdenny** [comment]
Today I was playing with appveyor, and more or less I have a clear idea of what to do with automatic build, versioning, etc... BUT.... **YES, I need a repo per package, if we want to trigger an automatic build for a specific package**

The process you describe is good, even if I have to investigate deeper how to separate the dev build from master build, and separate the publish into two different nuget feed. I have few ideas, for instance using environment variable {branch}, and with few pre-build scripts, creating a variable that is set with the url of the feed (based on the branch, dev->myget, master->nuget), then use that variable in the "Deployment" section.

I think you have to manage this task because you're the owner and can create new repo.

I stand-by on appveyor waiting this issue to be done.

**Comment by mauroservienti** [comment]
> The process you describe is good, even if I have to investigate deeper how to separate the dev build from master build, and separate the publish into two different nuget feed. I have few ideas, for instance using environment variable {branch}, and with few pre-build scripts, creating a variable that is set with the url of the feed (based on the branch, dev->myget, master->nuget), then use that variable in the "Deployment" section.

It is not a requirement I would die for, I mean: we can publish everything every time to `MyGet` only and then manually promote a package as a stable one to `NuGet`. In this way, we simply merge a 'release' branch on both `develop` and `master` using a tag to specify the `package` numbering strategy. Easy peasy.

**Comment by micdenny** [comment]
If I well understood, you will leave the repo as is (all the projects in one repo), and then on every commit, the build server automatically publish the packages to `MyGet` as `-beta` or whatever we specify in the appveyor config file. To publish a stable version, we merge on `master` branch, then use a tag that specify the version for the stable packages, and the build server should use that Tag as assembly / package version.

Do you mean that?

**Comment by mauroservienti** [comment]
no, not necessarily. We must separate each component (`Radical`, `Radical.Windows`, etc...) in its own repo, versioning is already a mess in a single repo.
Once we have component in its own repo I would like to have a build for each component, each component will be managed using GitFlow and each time we push a build is started and deployed to a feed.
Would be great to have, but not mandatory, to have that if we push to `develop` then we publish as `beta` to `Myget`, if we push to `release` then we publish to `NuGet`.

**Comment by micdenny** [comment]
> We must separate each component (Radical, Radical.Windows, etc...) in its own repo, versioning is already a mess in a single repo.

ok, I still like this idea :smile: 

> Once we have component in its own repo I would like to have a build for each component, each component will be managed using GitFlow and each time we push a build is started and deployed to a feed.

wilco!

> Would be great to have, but not mandatory, to have that if we push to develop then we publish as beta to Myget, if we push to release then we publish to NuGet.

copy!

Now, everything is clear, I standby waiting the projects to be separated on its own repo, then start testing the build process as we decided.

**Comment by mauroservienti** [comment]
this is done
