### ISSUE TITLE
RadicalFx new logo

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#2]
- [x] create the new log
- All NuGet packages
  - [x] Radical
  - [x] Radical.Windows
  - [x] Radical.Design
  - [x] Radical.Windows.Presentation
  - [x] Radical.Windows.Presentation.CastleWindsor
  - [x] Radical.Windows.Presentation.Autofac
  - [x] Radical.Windows.Presentation.Unity2
  - [x] Radical.Windows.Presentation.Unity3
- [x] Website
- All Readme files
  - [x] Radical
  - [x] Radical.Windows
  - [x] Radical.Design
  - [x] Radical.Windows.Presentation
  - [x] Radical.Windows.Presentation.CastleWindsor
  - [x] Radical.Windows.Presentation.Autofac
  - [x] Radical.Windows.Presentation.Unity2
  - [x] Radical.Windows.Presentation.Unity3
- [x] GitHub team/organization
- [x] VSIX Templates
- All Radical.CQRS packages
  - [x] Radical.CQRS.EntityFramework
  - [x] Radical.CQRS.Server
  - [x] Radical.CQRS.Handlers
  - [x] Radical.CQRS.Client
  - [x] Radical.CQRS
  - [x] Radical.CQRS.Messages
  - [x] Radical.CQRS.NHibernate (not on Nuget, yet)
- [x] Radical Universal repo
- [x] Radical Universal package(s)

logo proposal:

![radical_framework_orange_logo](https://cloud.githubusercontent.com/assets/1325611/5571873/3830a6fc-8f97-11e4-9dbf-508329d0b69a.png)

advantages:
- it is a font :-) the entire logo is a font + a bunch of CSS;
- the symbol is basically the indian rupee currency symbol but it is also `R`adical `F`ramework

**Comment by micdenny** [comment]
+1 I like the proposal

**Comment by mauroservienti** [comment]
I double checked all the nuget packages and they are correct, however on Nuget some of them are showing the wrong icon.
I'll close this for now, there is nothing we can do other then check as we release new packages.
