### ISSUE TITLE
Add missing nuspec(s)

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#22]
_From @mauroservienti on June 5, 2015 10:11_

null

_Copied from original issue: RadicalFx/Radical#174_

**Comment by mauroservienti** [comment]
@micdenny do we need to do something else or all the projects are updated to the new AppVeyor build system?

**Comment by micdenny** [comment]
All the Radical main projects has been updated and work on appveyor build system.

The one that is left is [Radical-VisualStudio-Templates](https://github.com/RadicalFx/Radical-VisualStudio-Templates) that could be add in CI as well, and probably in continuous delivery as well (if there's a way to programmatically push packages to visual studio gallery).

I think we can close this, and open an issue in Radical-VisualStudio-Templates to be integrated in appveyor.

**Comment by micdenny** [comment]
Sorry also [radical-universal](https://github.com/RadicalFx/radical-universal) is not on appveyor, but you're working on new version of it, so we can wait for that.

**Comment by mauroservienti** [comment]
Yeah, let's close this one. Universal support is far from being ready.
