### ISSUE TITLE
What about using shared projects instead of linked files?

### ISSUE THREAD

**Issue by micdenny** [RadicalFx/housekeeping#25]
I dream about having common projects and dedicated version projects only for files that differs, using shared project.

As far as I know in vs2013 this could be achieved using this [Shared Project Reference Manager](https://visualstudiogallery.msdn.microsoft.com/315c13a7-2787-4f57-bdf7-adae6ed54450) visual studio extension, but in vs2015 they add new, lets say native, [templates for shared project](https://www.visualstudio.com/news/vs2015-vs#VSIDE).

Any thoughts?

**Comment by mauroservienti** [comment]
I think it is a much better approach, that removes also the friction of keeping things in sync. I'll spike it and see if there is something that is missing.

**Comment by mauroservienti** [comment]
.NET Core 3 and .NET Standard are a better approach.
