### ISSUE TITLE
Radical Light

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#28]

**Comment by micdenny** [comment]
tough life :smoking:

**Comment by mauroservienti** [comment]
I completely forgot what was the idea behind this :smile:

**Comment by micdenny** [comment]
Probably having also something like MvvmLight? Only base features,
notification, broker, etc...

Il giovedì 24 dicembre 2015, Mauro Servienti notifications@github.com ha
scritto:

> I completely forgot what was the idea behind this [image: :smile:]
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167056179
> .

## 

Michael Denny
Engage IT Services s.r.l. http://www.engageitservices.it/
Software Architect, Trainer and Consultant
Microsoft MVP .NET
http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735
More about me http://about.me/micdenny

**Comment by mauroservienti** [comment]
And one single assembly?

On Thu, Dec 24, 2015 at 8:54 AM, Michael Denny notifications@github.com
wrote:

> Probably having also something like MvvmLight? Only base features,
> notification, broker, etc...
> 
> Il giovedì 24 dicembre 2015, Mauro Servienti notifications@github.com ha
> scritto:
> 
> > I completely forgot what was the idea behind this [image: :smile:]
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167056179
> > 
> > .
> 
> ## 
> 
> Michael Denny
> Engage IT Services s.r.l. http://www.engageitservices.it/
> Software Architect, Trainer and Consultant
> Microsoft MVP .NET
> http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735
> More about me http://about.me/micdenny
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167063887
> .

## 

Mauro Servienti

**Comment by micdenny** [comment]
Yes, probably something like that, in that case we can use the old-style
file linking on another project to re-use some code, now we need to
understand what put inside, I think a good way is to have exactly the same
as MvvmLight :)

Il giovedì 24 dicembre 2015, Mauro Servienti notifications@github.com ha
scritto:

> And one single assembly?
> 
> On Thu, Dec 24, 2015 at 8:54 AM, Michael Denny <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > Probably having also something like MvvmLight? Only base features,
> > notification, broker, etc...
> > 
> > Il giovedì 24 dicembre 2015, Mauro Servienti <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> ha
> > scritto:
> > 
> > > I completely forgot what was the idea behind this [image: :smile:]
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167056179
> > 
> > > .
> > 
> > ## 
> > 
> > Michael Denny
> > Engage IT Services s.r.l. http://www.engageitservices.it/
> > Software Architect, Trainer and Consultant
> > Microsoft MVP .NET
> > http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735
> > More about me http://about.me/micdenny
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167063887
> > 
> > .
> 
> ## 
> 
> Mauro Servienti
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167064230
> .

## 

Michael Denny
Engage IT Services s.r.l. http://www.engageitservices.it/
Software Architect, Trainer and Consultant
Microsoft MVP .NET
http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735
More about me http://about.me/micdenny

**Comment by mauroservienti** [comment]
We could also use `shared projects`, one interesting approach could be to convert all what we have to shared projects and then create projects only to link shared ones to package things and deploy, so basically shared projects could be something like feature/capability based.

**Comment by micdenny** [comment]
ok then, we have to check if the actual packages are in fact the minimal
set of what is need to create a light framework.

with that approach we could also think to have single assembly or at least
choose a different approach to install Radical, the fact that to install it
I have to choose the deeper package
`Radical.Windows.Presentation.CastleWindsor` is not easy to one is new to
Radical, a more convenient way could be to have just the "Radical" package
that by default is using castle (or puzzle) and all the default
dependencies we decide, then if you want another container you install it
over Radical, or of course have both ways, start from Radical.Castle or
Radical itself.

the last thing, a little bit out of the scope, is that embedding Radical
dll(s) in the application executable seems not to be possibile (this could
be a nice feature when you want to distribute an application in 1 file),
because some dll are loaded dynamically at runtime searching on physical
path, I had to exclude from embedding this files:
System.Windows.Interactivity.dll,
Radical.Windows.Presentation.CastleWindsor.dll,
Radical.Windows.Presentation.dll
probably I have to investigate deeper this, in that case I'm using
SmartAssembly (by redgate) and I should also try with `ILMerge` or
`ILRepack`.

On Thu, Dec 24, 2015 at 9:02 AM, Mauro Servienti notifications@github.com
wrote:

> We could also use shared projects, one interesting approach could be to
> convert all what we have to shared projects and then create projects only
> to link shared ones to package things and deploy, so basically shared
> projects could be something like feature/capability based.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167064610
> .

## 

Michael Denny
Engage IT Services s.r.l. http://www.engageitservices.it/
Software Architect, Trainer and Consultant
Microsoft MVP .NET
http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735
More about me http://about.me/micdenny

**Comment by mauroservienti** [comment]
> with that approach we could also think to have single assembly or at least
> choose a different approach to install Radical, the fact that to install it
> I have to choose the deeper package
> `Radical.Windows.Presentation.CastleWindsor` is not easy to one is new to
> Radical, a more convenient way could be to have just the "Radical" package
> that by default is using castle (or puzzle) and all the default
> dependencies we decide, then if you want another container you install it
> over Radical, or of course have both ways, start from Radical.Castle or
> Radical itself.

The need to start from a dependency to setup the toolkit is a nightmare, [the idea is to support Puzzle as the default container](https://github.com/RadicalFx/Radical.Windows.Presentation/issues/9) so that if there is no specific requirement for a container everything works out of the box.

**Comment by micdenny** [comment]
and I would like to just add "Radical" package to get everything
out-of-the-box

On Thu, Dec 24, 2015 at 3:35 PM, Mauro Servienti notifications@github.com
wrote:

> with that approach we could also think to have single assembly or at least
> choose a different approach to install Radical, the fact that to install it
> I have to choose the deeper package
> Radical.Windows.Presentation.CastleWindsor is not easy to one is new to
> Radical, a more convenient way could be to have just the "Radical" package
> that by default is using castle (or puzzle) and all the default
> dependencies we decide, then if you want another container you install it
> over Radical, or of course have both ways, start from Radical.Castle or
> Radical itself.
> 
> The need to start from a dependency to setup the toolkit is a nightmare, the
> idea is to support Puzzle as the default container
> https://github.com/RadicalFx/Radical.Windows.Presentation/issues/9 so
> that if there is no specific requirement for a container everything works
> out of the box.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/RadicalFx/housekeeping/issues/28#issuecomment-167118912
> .

## 

Michael Denny
Engage IT Services s.r.l. http://www.engageitservices.it/
Software Architect, Trainer and Consultant
Microsoft MVP .NET
http://mvp.microsoft.com/en-us/mvp/Michael%20Denny-5000735
More about me http://about.me/micdenny

**Comment by mauroservienti** [comment]
with the move to .NET Core Radical assemblies are now only 2 and I'm in the process of removing/obsoleting all what can be removed/obsoleted. In light if this I'm closing this, we can further reevaluate in the future.
