### ISSUE TITLE
Fix nuget packages icon

### ISSUE THREAD

**Issue by micdenny** [RadicalFx/housekeeping#29]
as you can see in some packages there's the icon in some other not: 

![image](https://cloud.githubusercontent.com/assets/1633595/11298491/a52f2240-8f7f-11e5-8ff2-04b2e419afa4.png)

all the radical nuget packages need the new radical icon:

![image](https://cloud.githubusercontent.com/assets/1633595/11298495/b1cd5e0e-8f7f-11e5-8c35-8d969bab6937.png)

**Comment by mauroservienti** [comment]
I should have fixed all the wrong icons, a few, most of them were correct. There are a couple of PR waiting for your review, then I think we can close this one.

**Comment by micdenny** [comment]
I've checked all the other radical repo and they are all fine, we can close this issue as soon as [Radical#10](https://github.com/RadicalFx/Radical.Windows.Presentation.CastleWindsor/pull/10) and [Radical.Windows.Presentation.CastleWindsor#201](https://github.com/RadicalFx/Radical/pull/201) has been close.

**Comment by mauroservienti** [comment]
this is done, the remaining of the work is tracked by #2
