### ISSUE TITLE
Reverse the DI container configuration responsibiltiy

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#34]
We have a strong dependency on a DI container, like it or not that's a fact.

Given the way things are actually designed implementing support for a container is a nightmare that comes to life. It is up to the user to understand what to register, how, when, and how to deal with `BootstrapConventions`. It is everything but a trivial task.

Now that we are going in the direction of a high level, DI container independent, `ApplicationBootstrapper` (See https://github.com/RadicalFx/Radical.Windows.Presentation/issues/21 and https://github.com/RadicalFx/radical-universal/issues/28) that utilizes a `IContainerBootstrapper` implementation as a mediator when talking to the DI container, I'm wondering if there is any value in moving the responsibility of deciding what to register, and how and when, to the `ApplicationBootstrapper` making the `IContainerBootstrapper` responsible for the physical registration only.

The clear advantage is that we move in the direction of making the task of implementing support for a new container a trivial task.

@micdenny thoughts?

**Comment by mauroservienti** [comment]
related to #6

**Comment by micdenny** [comment]
you can check how we did in EasyNetQ:

The container interface: [`IServiceProvider`](https://github.com/EasyNetQ/EasyNetQ/blob/a1d28cca528d6675b90960a8e6f410f0515ce559/Source/EasyNetQ/IServiceProvider.cs)

The default container implementation: [`DefaultServiceProvider`](https://github.com/EasyNetQ/EasyNetQ/blob/master/Source/EasyNetQ/DefaultServiceProvider.cs)

And until now is our [`PuzzleContainer`](https://github.com/RadicalFx/Radical/blob/develop/src/net35/Radical/Container/PuzzleContainer.cs)

The static helper to bootstrap the library: [`RabbitHutch`](https://github.com/EasyNetQ/EasyNetQ/blob/31d159c63a8998e210ce9bc50ca75dacc49ad19e/Source/EasyNetQ/RabbitHutch.cs)

as you can see we simple expose a [`SetContainerFactory`](https://github.com/EasyNetQ/EasyNetQ/blob/31d159c63a8998e210ce9bc50ca75dacc49ad19e/Source/EasyNetQ/RabbitHutch.cs#L20) method so you can really easily replace the container before calling the factory method:

``` csharp
RabbitHutch.SetContainerFactory(new WindsorAdapter(new WindsorContainer()));
```

and creating a container is really a trivial task: [`WindsorAdapter`](https://github.com/EasyNetQ/EasyNetQ/blob/master/Source/EasyNetQ.DI.Windsor/WindsorAdapter.cs)

**Comment by mauroservienti** [comment]
Withdrawing this as we moved to `IServiceCollection` as a mediator between Radical and IoC containers.
