### ISSUE TITLE
Commitment and maintainer group size

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#45]
At the time of this writing we have [12 pending PRs](https://github.com/search?p=1&q=org%3ARadicalFx+is%3Apr+is%3Aopen&ref=searchresults&type=Issues&utf8=%E2%9C%93) among which some quite old.

Obviously due to the fact that `Radical` is not our main focus, unfortunately we need to work as well, it is sometimes hard to commit, this is obviously complicated by the fact that the maintainer group is super small (@micdenny and I) and the `we cannot merge our own PRs` rule is causing some pain.

I actually see two possible approaches:
- Find and introduce at least one new maintainer. Super complex, reviewing other PRs requires great skills and requires deep knowledge of the framework itself. We can, however we need to take into account that it might take a lot of time
- put in place some W.I.P e.g. not more than 4 items in progress over the entire toolkit and at the same time try to enforce some commitment e.g. a PR should be reviewed within 3 days (whatever number we come up with is good)

@micdenny comments? thoughts?

**Comment by mauroservienti** [comment]
> put in place some W.I.P e.g. not more than 4 items in progress over the entire toolkit

Another option could be to use `story points` as WIP, what waffle.io calls `size`, this could be interesting cause it requires some effort at the `Ready` stage to determine the size/effort required and can be used similar to the usage of velocity done by Scrum

**Comment by mauroservienti** [comment]
> over the entire toolkit

Means that in this board https://waffle.io/radicalfx/housekeeping the WIP limit will be applied to the `In progress` column.

**Comment by micdenny** [comment]
yes this could become frustrating, because the PR committer is super exited of its function and would like to have a fast review so to be productive and eventually re-iterating fast, but as far as I saw in OSS developing this is an easy to fall-in condition, especially as you said when no one of the team are mostly committed on the project, and I think this is the problem, but to avoid such a delay probably your idea, to avoid taking care of too much features at the same time, is a good approach, I'm not sure about the reviews in XX days, I mean what is the fallback? If the team does not commit in XX days what happen apart the public humiliation :smile: ?

**Comment by mauroservienti** [comment]
> I'm not sure about the reviews in XX days, I mean what is the fallback? If the team does not commit in XX days what happen apart the public humiliation :smile: ?

Completely agree, worth nothing. I was just throwing ideas on the table trying to improve the situation.
So, what about starting with the WIP limit?

**Comment by micdenny** [comment]
> what about starting with the WIP limit?

that's ok to me, I would start simply doing it :) I mean we decide a limit then we try to follow it ;)

**Comment by mauroservienti** [comment]
What about 4? that could mean 2 each.

**Comment by micdenny** [comment]
ok 2 each! agreed

**Comment by mauroservienti** [comment]
We now have [9 in progress issues](https://waffle.io/radicalfx/housekeeping) globally, most of them depends on the GitVersion migration, once the whole migration is done, I'll ping you were I think I'll need you.

**Comment by micdenny** [comment]
ok great, thank you!

**Comment by mauroservienti** [comment]
Not a thing we can really solve. Closing.
