### ISSUE TITLE
Remove Radical.Build repo

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#48]
Depends on #35. if not needed anymore remove the Radical.Build repo

**Comment by micdenny** [comment]
I search for any usage of it, nothing found, I drop the repo.

**Comment by micdenny** [comment]
done

**Comment by micdenny** [comment]
this is the backup of the repo (how is it cool this upload feature! :smile:)

[Radical.Build-master.zip](https://github.com/RadicalFx/housekeeping/files/213527/Radical.Build-master.zip) (no history)

**Comment by mauroservienti** [comment]
Yeah. :+1:
