### ISSUE TITLE
Radical.Windows.Presentation should be merged into Radical.Windows

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#64]
There is really nothing that stops us from merging the MVVM stuff into WPF stuff.
This has the benefit of reducing the dependencies from the end user perspective.

Any cons?

**Comment by micdenny** [comment]
I don't see any cons

**Comment by mauroservienti** [comment]
done in https://github.com/RadicalFx/Radical.Windows/pull/111
