### ISSUE TITLE
Add "ShouldHandle" behavior to broker

### ISSUE THREAD

**Issue by melkio** [RadicalFx/housekeeping#68]
`IMessageBroker` doesn't support the possibility to add "filter" during subscription phase.

I'd like to have something like:

```
broker.Subscribe<T>( object subscriber, Predicate<object, T> shouldHandle, Action<object, T> callback );
```

to avoid filtering inside callback implementation

**Comment by mauroservienti** [comment]
This issue was moved to RadicalFx/Radical#239
