### ISSUE TITLE
Domain registration for Radical

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#7]
Currently everything is hosted under "topics.it" as radical.topics.it. I think we should move away from my domain and register a dedicated one.
Unfortunately "Radical" is a very common world :-|
- [x] radicalframework.com;
- [x] radicalframework.it;

ideas are welcome :-)

**Comment by micdenny** [comment]
with the same idea changing also the root namespace could be a drama? :smiling_imp:

**Comment by mauroservienti** [comment]
I thought about it for months, it is a drama, a huge breaking change, catastrophic I'd say :-|
@enosrecanati we can do that in the Universal App repo, since we have not yet released anything. I'll setup an issue for that

**Comment by micdenny** [comment]
so we have the new domain? :smile:

**Comment by mauroservienti** [comment]
yes :) registred both:
- radicalframework.com;
- radicalframework.it;

A couple of minutes ago.

**Comment by micdenny** [comment]
great news! :dancers:
