### ISSUE TITLE
Can "Build.Support" repo be deleted?

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#71]

**Comment by micdenny** [comment]
I would just remove it, and I will do it, because if there's some repo left depending on it, we already know [we have a fix](https://github.com/RadicalFx/Radical.Windows/blob/develop/appveyor.yml#L22):

```yaml
  before_build:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.2.0/nuget.exe
    - nuget restore "src\Radical.Windows.sln"
```

**Comment by micdenny** [comment]
done!
