### ISSUE TITLE
Change the root namespace from Topics.Radical to Radical

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#8]
Which is the impact?

**Comment by micdenny** [comment]
someone @mauroservienti (#7) would say "catastrophic" :smile:

**Comment by mauroservienti** [comment]
The plan could be:
- drop the initial "Topics." from everywhere;
- add a readme to each nuget package to explain what is going on and how to fix your code;
- apologize for the pain :-)
- add entries for the XmlNamespaces to point to the new namespace, do not remove the old one;
- update the VSIX templates to reflect the above changes;
- use SemVer to communicate the painful change

**Comment by micdenny** [comment]
especially this `add entries for the XmlNamespaces to point to the new namespace, do not remove the old one;` could be a great idea, so at least the xaml could be leave as is for a while, I would say to leave the old xmlns until the next major release.

Is out there any facility to redirect a namespace to another for whom is so lazy? something like `assembly binding redirect`...

**Comment by mauroservienti** [comment]
Since we claim we use SemVer we could think to a v2 release of all the nugets including this.

**Comment by mauroservienti** [comment]
Type Forwarding could be an interesting option to investigate: https://msdn.microsoft.com/en-us/library/ms404275(v=vs.110).aspx

**Comment by micdenny** [comment]
> Since we claim we use SemVer we could think to a v2 release of all the nugets including this.

Yes, I think we should do this coupled with the dropping of net35/net40

> Type Forwarding could be an interesting option to investigate: https://msdn.microsoft.com/en-us/library/ms404275(v=vs.110).aspx

I don't understand if it can work with namespace instead of assemblies.

**Comment by mauroservienti** [comment]
I doubt it works

**Comment by mauroservienti** [comment]
this is done as part of #72
