### ISSUE TITLE
Setup a common "Microsoft Account" to handle the Visual Studio Gallery login

### ISSUE THREAD

**Issue by mauroservienti** [RadicalFx/housekeeping#9]

**Comment by micdenny** [comment]
@mauroservienti Do you want to do this, or could I take it? the problem is how to migrate the old package to the new microsoft account owner.

It would be nice to go ahead with this and [deploy the new templates](https://github.com/RadicalFx/Radical-VisualStudio-Templates/issues/18).

**Comment by mauroservienti** [comment]
Go for it, setup a new account share the password.
After that assign the issue to me, I'll delete the template from my account so we can publish the new one.

Sent from my Amazing not anymore Yellow Lumia, typos are guaranteed ;-)

**Comment by micdenny** [comment]
Done!

[Social Profile](https://social.msdn.microsoft.com/profile/radical%20framework/)

I'll send the user access by email.

**Comment by micdenny** [comment]
sent!
